---
version: "3.5"
volumes:
    mysql_db_data_container:

networks:
  frontend:
    external:
      name: frontend

services:
  adminer:
    container_name: adminer
    image: library/adminer:latest
    hostname: adminer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # networks:
      # backend:
        # ipv4_address: 172.30.0.2
    ports:
      - 18080:8080
    volumes:
      - ${CONTAINERS}/adminer:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ADMINER_DEFAULT_SERVER: mysql_db_container
      ADMINER_DESIGN: galkaev

    mysql_db_container:
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        env_file:
          - ./config/mysql.env
        ports:
          - 3307:3307
        volumes:
            - mysql_db_data_container:/var/lib/mysql

