---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/Volume2/docker/containers/bookstack/data:/config
    ports:
      - 18081:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /mnt/Volume2/docker/containers/bookstack/DB:/config
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: library/adminer:latest
    hostname: adminer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # networks:
      # backend:
        # ipv4_address: 172.30.0.2
    ports:
      - 18080:8080
    volumes:
      - ${CONTAINERS}/adminer:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
